name: coverage

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run-coverage:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda env & dependencies
      run: |
        conda install python=${{ matrix.python-version }}
        pip install -e '.[atari, mujoco, envpool, pettingzoo, onnx]'
        conda list
    - name: Install codecov dependencies
      run: |
        pip install pytest
        pip install pytest-cov
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-config=./.core-coveragerc --cov-report=xml -v
        ls -al
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: /home/runner/work/sample-factory/sample-factory/coverage.xml
        verbose: true
